# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[constraint]]
#  name = "github.com/x/y"
#  version = "2.4.0"



required = [
  "github.com/Azure/go-autorest/autorest",
  "github.com/docker/distribution/reference",
  "k8s.io/api/core/v1",
  "k8s.io/apimachinery/pkg/apis/meta/v1",
  "k8s.io/apiserver/pkg/endpoints/request",
]



[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "9.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/docker/distribution"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/apiextensions"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/apprclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/backoff"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/certs"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/clusterclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/errors"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/helmclient"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/kubeconfig"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microendpoint"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microerror"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/microkit"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/micrologger"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/operatorkit"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/resource"

[[constraint]]
  branch = "master"
  name = "github.com/giantswarm/tenantcluster"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.4"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.14.3"

[[constraint]]
  name = "sigs.k8s.io/cluster-api"
  version = "v0.1.10"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.15.4"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.15.4"

[[override]]
  name = "k8s.io/component-base"
  version = "kubernetes-1.15.4"

[[override]]
  name = "github.com/ghodss/yaml"
  branch = "master"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "v1.5.2"



[prune]
  go-tests = true
  unused-packages = true
