apiVersion: v1
name: cluster-operator
description: The cluster-operator manages Kubernetes tenant cluster resources.
home: https://github.com/giantswarm/cluster-operator
version: [[ .Version ]]
appVersion: [[ .AppVersion ]]
annotations:
  config.giantswarm.io/version: 1.x.x