image:
  name: "giantswarm/cluster-operator"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: docker.io
pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
