image:
  name: "giantswarm/cluster-operator"
  tag: "[[ .Version ]]"

pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

registry:
  domain: gsoci.azurecr.io
  mirrors:
    - giantswarm.azurecr.io
  pullSecret:
    dockerConfigJSON: ""

  dockerhub:
    token: token

cni:
  mask: 16
  subnet: 10.1.0.0/16

kubernetes:
  api:
    clusterIPRange: 172.31.0.0/16
  clusterDomain: cluster.local

provider:
  kind: ""

installation:
  name: ""

release:
  app:
    config:
      default: |
        catalog: default
        namespace: kube-system
        useUpgradeForce: true
      kiamWatchdogEnabled: true
      override: |
        cert-exporter:
          chart: "cert-exporter"
        # chart-operator must be installed first so the chart CRD is
        # created in the tenant cluster.
        chart-operator:
          chart:     "chart-operator"
          namespace: "giantswarm"
        # Upgrade force is disabled to avoid affecting customer workloads.
        coredns:
          useUpgradeForce: false
        net-exporter:
          chart: "net-exporter"

vault:
  certificate:
    ttl: 4320h

# Add seccomp to pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
      - ALL

global:
  podSecurityStandards:
    enforced: false
