version: 2.1
orbs:
  architect: giantswarm/architect@0.10.1

workflows:
  build_and_push:
    jobs:
      # build binary
      - architect/go-build:
          name: go-build
          binary: cluster-operator
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to quay
      - architect/push-to-docker:
          name: push-cluster-operator-to-quay
          image: "quay.io/giantswarm/cluster-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to aliyun (only PRs branches)
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # requires manual approval
          requires:
            - build
          filters:
            tags:
              ignore: /^v.*/

      # build and push docker image to aliyun (only tags)
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-tag
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # build and push chart to app catalog
      - architect/push-to-app-catalog:
          name: push-cluster-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-operator"
          # Make sure docker image is successfully built.
          requires:
            - push-cluster-operator-to-quay
          filters:
            tags:
              only: /^v.*/
