version: 2.1
orbs:
  architect: giantswarm/architect@0.4.5

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version

    - run: |
        date +"%Y" > /tmp/year
        date +"%m" > /tmp/month
        date +"%d" > /tmp/day
    - restore_cache:
        keys:
        - go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}-{{ checksum "/tmp/day" }}
        - go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}
        - go-cache-v1-{{ checksum "/tmp/year" }}

    - run: ./architect build

    - store_test_results:
        path: /tmp/results

    - save_cache:
        key: go-cache-v1-{{ checksum "/tmp/year" }}-{{ checksum "/tmp/month" }}-{{ checksum "/tmp/day" }}
        paths:
        - /tmp/go/cache

    - persist_to_workspace:
        root: .
        paths:
        - ./cluster-operator
        - ./architect

  deploy:
    machine: true
    steps:
    - checkout
    - attach_workspace:
        at: .
    - deploy:
        command: |
            ./architect deploy

workflows:
  build_and_push:
    jobs:
      - build
      - architect/push-to-docker:
          name: push-cluster-operator-to-quay
          image: "quay.io/giantswarm/cluster-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build

      - hold-push-cluster-operator-to-aliyun-pr:
          type: approval
          requires:
            - build
          # Needed to prevent job from being triggered on thiccc branch.
          filters:
            branches:
              ignore: thiccc

      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-thiccc branches only once manually approved.
          requires:
            - hold-push-cluster-operator-to-aliyun-pr
          # Needed to prevent job from being triggered on thiccc branch.
          filters:
            branches:
              ignore: thiccc

      # Push to Aliyun should execute without manual approval on thiccc.
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-thiccc
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to thiccc.
          filters:
            branches:
              only: thiccc

      - deploy:
          name: deploy
          requires:
            - push-cluster-operator-to-aliyun-thiccc
            - push-cluster-operator-to-quay
          filters:
            branches:
              only: thiccc

