version: 2.1

orbs:
  architect: giantswarm/architect@0.10.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: cluster-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cluster-operator-to-quay
          image: "quay.io/giantswarm/cluster-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-cluster-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-operator"
          requires:
            - push-cluster-operator-to-quay
          filters:
            tags:
              only: /^v.*/
