version: 2.1
orbs:
  architect: giantswarm/architect@0.10.0

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version
    - run: ./architect build
    - store_test_results:
        path: /tmp/results
    - persist_to_workspace:
        root: .
        paths:
        - ./cluster-operator

workflows:
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-cluster-operator-to-quay
          image: "quay.io/giantswarm/cluster-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      - hold-push-cluster-operator-to-aliyun-pr:
          type: approval
          requires:
            - build
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^v.*/

      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - hold-push-cluster-operator-to-aliyun-pr
          # Needed to prevent job from being triggered on master branch.
          filters:
            branches:
              ignore: master
            tags:
              ignore: /^v.*/

      # Push to Aliyun should execute without manual approval on master.
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-tag
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          # Needed to trigger job only on merge to master.
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-cluster-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-operator"
          # Make sure docker image is successfully built.
          requires:
            - push-cluster-operator-to-quay
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-cluster-operator-to-aws-app-collection
          app_name: "cluster-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-cluster-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-cluster-operator-to-azure-app-collection
          app_name: "cluster-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-cluster-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: push-cluster-operator-to-kvm-app-collection
          app_name: "cluster-operator"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-cluster-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
