version: 2.1
orbs:
  architect: giantswarm/architect@0.10.1

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: Install architect
        command: |
          architect_version="2.1.0"
          curl -fsSL https://github.com/giantswarm/architect/releases/download/v${architect_version}/architect-v${architect_version}-linux-amd64.tar.gz | tar -xzv --strip-components 1 --wildcards '*/architect'
          ./architect version
    - run:
        name: Build
        command: ./architect build
    - store_test_results:
        path: /tmp/results
    - persist_to_workspace:
        root: .
        paths:
        - ./cluster-operator

workflows:
  build_and_push:
    jobs:
      # build binary
      - build:
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to quay
      - architect/push-to-docker:
          name: push-cluster-operator-to-quay
          image: "quay.io/giantswarm/cluster-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          filters:
            tags:
              only: /^v.*/

      # build and push docker image to aliyun (only PRs branches)
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # requires manual approval
          requires:
            - build
          filters:
            tags:
              ignore: /^v.*/

      # build and push docker image to aliyun (only tags)
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-tag
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # build and push chart to app catalog
      - architect/push-to-app-catalog:
          name: push-cluster-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-operator"
          # Make sure docker image is successfully built.
          requires:
            - push-cluster-operator-to-quay
          filters:
            tags:
              only: /^v.*/

      # deploy to aws installations (only tags)
      - architect/push-to-app-collection:
          name: push-cluster-operator-to-aws-app-collection
          app_name: "cluster-operator"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-cluster-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to azure installations (only tags)
      - architect/push-to-app-collection:
          name: push-cluster-operator-to-azure-app-collection
          app_name: "cluster-operator"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-cluster-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      # deploy to kvm installations (only tags)
      - architect/push-to-app-collection:
          name: push-cluster-operator-to-kvm-app-collection
          app_name: "cluster-operator"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-cluster-operator-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
