version: 2.1
orbs:
  architect: giantswarm/architect@0.4.3

jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version
    - run: ./architect build
    - store_test_results:
        path: /tmp/results
    - persist_to_workspace:
        root: .
        paths:
        - ./cluster-operator

workflows:
  build_and_push:
    jobs:
      - build

      - architect/push-to-docker:
          name: push-cluster-operator-to-quay
          image: "quay.io/giantswarm/cluster-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build

      - hold-push-cluster-operator-to-aliyun-pr:
          type: approval
          requires:
            - build
          filters:
            # Needed to prevent job from being triggered on legacy branch.
            branches:
              ignore: legacy

      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-pr
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-legacy branches only once manually approved.
          requires:
            - hold-push-cluster-operator-to-aliyun-pr
          filters:
            # Needed to prevent job from being triggered on legacy branch.
            branches:
              ignore: legacy

      # Push to Aliyun should execute without manual approval on legacy.
      - architect/push-to-docker:
          name: push-cluster-operator-to-aliyun-legacy
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/cluster-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - build
          filters:
            # Needed to trigger job only on merge to legacy.
            branches:
              only: legacy
