version: 2.1

orbs:
  architect: giantswarm/architect@5.1.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: cluster-operator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-cluster-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
