apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-operator-configmap
  namespace: {{ .Values.namespace }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        calico:
          subnet: '{{ .Values.Installation.V1.Guest.Calico.Subnet }}'
          cidr: '{{ .Values.Installation.V1.Guest.Calico.CIDR }}'
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.Installation.V1.Guest.Kubernetes.API.ClusterIPRange }}'
        vault:
          certificate:
            ttl: '{{ .Values.Installation.V1.Auth.Vault.Certificate.TTL }}'
    service:
      clusterService:
        address: 'http://cluster-service:8000'
      image:
        registry:
          domain: '{{ .Values.Installation.V1.Registry.Domain }}'
      kubeconfig:
        resource:
          namespace: 'giantswarm'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      provider:
        kind: '{{ .Values.Installation.V1.Provider.Kind }}'
