apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-operator-configmap
  namespace: giantswarm
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.Installation.V1.Guest.Kubernetes.API.ClusterIPRange }}'
        vault:
          certificate:
            ttl: '{{ .Values.Installation.V1.Auth.Vault.Certificate.TTL }}'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      registryDomain: '{{ .Values.Installation.V1.Registry.Domain }}'
