apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-operator-configmap
  namespace: giantswarm
data:
  config.yml: |
    server:
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        azure:
          hostCluster:
            cidr: '{{ .Values.Installation.V1.Provider.Azure.HostCluster.CIDR }}'
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.Installation.V1.Guest.Kubernetes.API.ClusterIPRange }}'
        network:
          cidr: '{{ .Values.Installation.V1.Guest.IPAM.NetworkCIDR }}'
        vault:
          certificate:
            ttl: '{{ .Values.Installation.V1.Auth.Vault.Certificate.TTL }}'
    service:
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      storage:
        kind: crd
