apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - cluster-operator-configmap
    verbs:
      - get
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - core.giantswarm.io
    resources:
      - awsclusterconfigs
      - azureclusterconfigs
      - certconfigs
      - clusternetworkconfigs
      - clusternetworkconfigs/status
      - kvmclusterconfigs
      - storageconfigs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-operator
subjects:
  - kind: ServiceAccount
    name: cluster-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: cluster-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - cluster-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-operator-psp
subjects:
  - kind: ServiceAccount
    name: cluster-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: cluster-operator-psp
  apiGroup: rbac.authorization.k8s.io
