apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "cluster-operator.labels" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        calico:
          subnet: '{{ .Values.Installation.V1.Guest.Calico.Subnet }}'
          cidr: '{{ .Values.Installation.V1.Guest.Calico.CIDR }}'
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.Installation.V1.Guest.Kubernetes.API.ClusterIPRange }}'
          domain: '{{ .Values.Installation.V1.Guest.Kubernetes.ClusterDomain }}'
        vault:
          certificate:
            ttl: '{{ .Values.Installation.V1.Auth.Vault.Certificate.TTL }}'
    service:
      clusterService:
        address: 'http://cluster-service:8000'
      image:
        registry:
          domain: '{{ .Values.Installation.V1.Registry.Domain }}'
      kubeconfig:
        resource:
          namespace: 'giantswarm'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      provider:
        kind: '{{ .Values.Installation.V1.Provider.Kind }}'
      release:
        app:
          config:
            default: {{ toYaml .Values.Installation.V1.GiantSwarm.Release.App.Config.Default | indent 12 }}
            override: {{ toYaml .Values.Installation.V1.GiantSwarm.Release.App.Config.Override | indent 12 }}
