apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        calico:
          subnet: '{{ .Values.cni.subnet }}'
          cidr: '{{ .Values.cni.mask }}'
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.kubernetes.api.clusterAPIRange }}'
        vault:
          certificate:
            ttl: '{{ .Values.vault.certificate.ttl }}'
    service:
      clusterService:
        address: 'http://cluster-service:8000'
      image:
        registry:
          domain: '{{ .Values.registry.domain }}'
      kubeconfig:
        resource:
          namespace: 'giantswarm'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      provider:
        kind: '{{ .Values.provider.kind }}'
      release:
        app:
          config:
            default: {{ toYaml .Values.release.app.config.default | indent 12 }}
            override: {{ toYaml .Values.release.app.config.override | indent 12 }}
