apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        calico:
          subnet: '{{ .Values.cni.subnet }}'
          cidr: '{{ .Values.cni.mask }}'
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.kubernetes.api.clusterIPRange }}'
          domain: '{{ .Values.kubernetes.clusterDomain }}'
        vault:
          certificate:
            ttl: '{{ .Values.vault.certificate.ttl }}'
    service:
      image:
        registry:
          domain: '{{ .Values.registry.domain }}'
      kubeconfig:
        resource:
          namespace: 'giantswarm'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      provider:
        kind: '{{ .Values.provider.kind }}'
      release:
        app:
          config:
            default: {{ toYaml .Values.release.app.config.default | indent 12 }}
            kiamWatchdogEnabled: {{ .Values.kiamWatchdogEnabled | quote }}
            override: {{ toYaml .Values.release.app.config.override | indent 12 }}
            dependencies: |-
              {
                "azure-cloud-controller-manager": [],
                "azure-cloud-node-manager": [],
                "azuredisk-csi-driver": [],
                "azurefile-csi-driver": [],
                "cert-exporter": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "chart-operator": [],
                "coredns": ["azure-cloud-controller-manager", "azure-cloud-node-manager"],
                "etcd-kubernetes-resources-count-exporter": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "external-dns": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "kube-state-metrics": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "metrics-server": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "net-exporter": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "node-exporter": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "cluster-autoscaler": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler"],
                "azure-scheduled-events": [],
                "vertical-pod-autoscaler": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns", "vertical-pod-autoscaler-crd"],
                "vertical-pod-autoscaler-crd": [],
                "observability-bundle": [],
                "k8s-dns-node-cache": ["azure-cloud-controller-manager", "azure-cloud-node-manager", "coredns"]
              }
