apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    guest:
      cluster:
        baseDomain: '{{ .Values.Installation.V1.Guest.Kubernetes.API.EndpointBase }}'
        calico:
          subnet: '{{ .Values.Installation.V1.Guest.Calico.Subnet }}'
          cidr: '{{ .Values.Installation.V1.Guest.Calico.CIDR }}'
        kubernetes:
          api:
            clusterIPRange: '{{ .Values.Installation.V1.Guest.Kubernetes.API.ClusterIPRange }}'
          domain: '{{ .Values.Installation.V1.Guest.Kubernetes.ClusterDomain }}'
    service:
      image:
        registry:
          domain: '{{ .Values.Installation.V1.Registry.Domain }}'
      kubeconfig:
        resource:
          namespace: 'giantswarm'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
      release:
        app:
          config:
            default: {{ toYaml .Values.Installation.V1.GiantSwarm.Release.App.Config.Default | indent 12 }}
            override: {{ toYaml .Values.Installation.V1.GiantSwarm.Release.App.Config.Override | indent 12 }}
