---
Installation:
  V1:
    GiantSwarm:
      Release:
        App:
          Config:
            Default: ""
            Override: ""
    Guest:
      Kubernetes:
        API:
          ClusterIPRange: ""
          EndpointBase: ""
        ClusterDomain: ""
    Provider:
      Kind: ""
    Registry:
      Domain: ""
